name: PKG PR New Test
on:
  push:
    branches:
      - feature/pkg-pr-new-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: npx pkg-pr-new publish
